name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio de código fuente
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Clonar el repositorio que contiene el Dockerfile
      - name: Clone Dockerfile Repository
        run: |
          git clone https://github.com/sergio-saavedra-arizaga/argocd-test.git dockerfile-repo

      # 2. Iniciar sesión en GitHub Container Registry (o Docker Hub)
      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io  # Cambia esto a `docker.io` si usas Docker Hub
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}

      # 3. Construir y etiquetar la imagen Docker
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/tu-usuario/prueba:latest -f dockerfile-repo/Dockerfile .

      # 4. Subir la imagen Docker al registro
      - name: Push Docker Image
        run: |
          docker push ghcr.io/tu-usuario/prueba:latest
